export const SET_EXPENSES = 'SET_EXPENSES'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const EDIT_EXPENSE = 'EDIT_EXPENSE'
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE'
export const LOADING_USER_START = 'LOADING_USER_START'
export const LOADING_EXPENSE_START = 'LOADING_EXPENSE_START'

export const SET_USER_DATA = 'SET_USER_DATA'